name: Remove old artifacts

# see: https://github.com/c-hive/gha-remove-artifacts

on:
  schedule:
    # Every month at 1 day 1am
    - cron: '0 2 1 * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 week'
          skip-tags: true